# Generated by Django 3.0.1 on 2019-12-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppUserName', models.CharField(max_length=50)),
                ('AppUserPassword', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
