# Generated by Django 3.0.1 on 2020-01-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ItemGroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcategory_title', models.CharField(max_length=200)),
                ('itemcategory_title_bangla', models.CharField(blank=True, max_length=200, null=True)),
                ('itemcategory_code', models.CharField(blank=True, max_length=200, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('ItemGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemGroup.ItemGroup')),
            ],
        ),
    ]
