# Generated by Django 2.2.9 on 2019-12-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcategory_title', models.CharField(max_length=200)),
                ('itemcategory_title_bangla', models.CharField(blank=True, max_length=200, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('create_by', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=200, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('delete_by', models.CharField(blank=True, max_length=200, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
