# Generated by Django 3.0.1 on 2020-01-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemCategory', '0002_auto_20200105_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='isactive',
            new_name='IsActive',
        ),
    ]
