# Generated by Django 3.0.1 on 2020-01-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPackSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemPackSizeName', models.CharField(max_length=120)),
                ('ItemPackSizeDesc', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('CreatedDate', models.DateTimeField(blank=True, null=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('DeletedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('DeletedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
