# Generated by Django 3.0.1 on 2020-01-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=200)),
                ('SupplierPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('SupplierEmail', models.CharField(blank=True, max_length=150, null=True)),
                ('SupplierWebsite', models.URLField(blank=True, max_length=500, null=True)),
                ('SupplierCountry', models.CharField(blank=True, max_length=200, null=True)),
                ('SupplierAddress', models.CharField(max_length=500)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('CreatedDate', models.DateTimeField(blank=True, null=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('DeletedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('DeletedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
