# Generated by Django 3.0.1 on 2019-12-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitofMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitbasisname', models.CharField(choices=[('Length (Measurable)', 'Length (Measurable)'), ('Mass & Weight (Weightable)', 'Mass & Weight (Weightable)'), ('Capacity & Volume (Weightable)', 'Capacity & Volume (Weightable)'), ('Countable', 'Countable')], max_length=100)),
                ('uom_name', models.CharField(max_length=200)),
                ('uom_shortname', models.CharField(max_length=50)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitofMeasureDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uomdetails_name', models.CharField(max_length=200)),
                ('uomdetails_shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('isbaseuom', models.BooleanField(default=False)),
                ('convertionvalue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('uomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnitofMeasure.UnitofMeasure')),
            ],
        ),
    ]
