# Generated by Django 3.0.1 on 2020-01-03 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnitofMeasure', '0002_auto_20200102_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasuredetails',
            name='uomid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UnitofMeasure.UnitofMeasure'),
        ),
    ]
