# Generated by Django 3.0.1 on 2020-01-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnitofMeasure', '0003_auto_20200103_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasuredetails',
            name='uomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnitofMeasure.UnitofMeasure'),
        ),
    ]
