# Generated by Django 3.0.1 on 2020-01-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnitofMeasure', '0004_auto_20200103_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
