# Generated by Django 3.0.1 on 2020-01-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemColor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcolor',
            old_name='isactive',
            new_name='IsActive',
        ),
    ]
