# Generated by Django 3.0.1 on 2020-01-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ItemBrand', '0002_auto_20200105_1258'),
        ('UnitofMeasure', '0007_auto_20200105_1258'),
        ('ItemPackSize', '0001_initial'),
        ('ItemCategory', '0002_auto_20200105_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=150)),
                ('ItemDescription', models.CharField(max_length=500)),
                ('ItemCode', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
                ('Remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('CreatedDate', models.DateTimeField(blank=True, null=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('DeletedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('DeletedDate', models.DateTimeField(blank=True, null=True)),
                ('ItemBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemBrand.ItemBrand')),
                ('ItemCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemCategory.ItemCategory')),
                ('ItemPackSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemPackSize.ItemPackSize')),
                ('Uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UnitofMeasure.UnitofMeasure')),
            ],
        ),
    ]
